---
title: "Analysis: tissue loss over 3-months"
author: "Julianna Renzi"
date: "2026-03-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r clear environment}
# clear environment for reproducibility
rm(list=ls())
```

```{r load packages}
# load librarian (package for installing/loading packages)
if (!require("librarian")) install.packages("librarian")

# load required packages
librarian::shelf(here, # relative file paths 
                 tidyverse, # data wrangling
                 glmmTMB, # model creation
                 car, # type II ANOVA
                 emmeans, # marginal means
                 performance # check model assumptions
                 )
```

```{r set color palette}
"#E1BE6A" -> no.snail.col
"#40B0A6" -> snail.col

"#c49627" -> no.snail.col.dark
"#2d7d76" -> snail.col.dark
```

# Bring in data

```{r}
# tissue cover data
tissue_1 <- read_csv(here("data", "tissue_cover.csv"))

# metadata
metadata <- read_csv(here("data", "metadata.csv"))
```

# Prepare data

```{r}
tissue_1 %>% 
  # add metadata
  full_join(metadata) %>% 
  # filter out corals we need to exclude
  filter(is.na(exclude_date)) %>% 
  # calculate tissue loss
  mutate(tissue_loss_percent = 100 - tissue_cover_3mo) %>% 
  # get labels nice
  mutate(treatment_skeleton = case_when(treatment_skeleton == "control" ~ "Control",
                                        treatment_skeleton == "hali" ~ "Halimeda skeleton",
                                        treatment_skeleton == "loboph" ~ "Lobophora skeleton",
                                        treatment_skeleton == "skeleton" ~ "Skeleton")) %>% 
  # and in the correct order
  mutate(treatment_skeleton = factor(treatment_skeleton, 
                                     levels = c("Control", "Skeleton", "Halimeda skeleton", "Lobophora skeleton"))) -> tissue_2
```

# Plot

```{r}
pdf(here("figures", "fig_S3_tissue.pdf"), height = 3, width = 4.5)

tissue_2 %>% 
  ggplot(aes(x = treatment_skeleton, y = tissue_loss_percent, fill = treatment_drupella)) +
  geom_boxplot(outliers = FALSE) +
  geom_jitter(aes(color = treatment_drupella),
              #color = "black", shape = 21, alpha = 0.5
              width = 0.15, size = 2, shape = 1, height = 0) + # use hollow circles
  scale_color_manual(name = "Snail wound", labels = c("n" = "No", "y" = "Yes"),
                     values = c(no.snail.col.dark, snail.col.dark)) +
  scale_fill_manual(name = "Snail wound", labels = c("n" = "No", "y" = "Yes"),
                     values = c(no.snail.col, snail.col)) +
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
        legend.position = "top", axis.text.x = element_markdown(lineheight = 1)) +
  ylab("Tissue loss (%)") +
  xlab("") +  
  scale_x_discrete(
    labels = (c("Control" = "Control", "Skeleton" = "Skeleton",
                "Halimeda skeleton" = "<i>Halimeda</i><br>skeleton",
                "Lobophora skeleton" = "<i>Lobophora</i><br>skeleton")))

dev.off()
```

# Model

With interaction

```{r}
m1 <- glmmTMB(tissue_loss_percent ~ treatment_skeleton + treatment_drupella + treatment_skeleton:treatment_drupella + (1|parent_colony), 
              family = tweedie(link = "log"),
              data = tissue_2)
```

```{r}
car::Anova(m1)
```

Drop interaction

```{r}
m2 <- glmmTMB(tissue_loss_percent ~ treatment_skeleton + treatment_drupella + (1|parent_colony), 
              family = tweedie(link = "log"),
              data = tissue_2)
```

```{r}
car::Anova(m2)
```

Check model assumptions

```{r}
check_model(m2) # looks good
```


